# Generated by Django 3.2 on 2021-10-26 06:22

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='path',
            field=models.CharField(default=django.db.models.fields.NullBooleanField, max_length=100),
        ),
    ]
