# Generated by Django 3.2 on 2021-10-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_transactions_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='members',
            name='flat',
            field=models.IntegerField(default=0),
        ),
    ]
