# Generated by Django 3.2 on 2021-10-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211026_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='From',
            new_name='From_mon',
        ),
    ]
