# Generated by Django 3.2 on 2021-10-28 07:22

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_from_transactions_from_mon'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='designation',
            field=models.CharField(default=django.db.models.fields.NullBooleanField, max_length=20),
        ),
    ]
