# Generated by Django 3.2 on 2021-10-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211030_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='employe',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('Present', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('Available', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('phone', models.IntegerField(default=None)),
            ],
        ),
    ]
