# Generated by Django 3.2 on 2021-10-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_employe'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
        ),
    ]
