# Generated by Django 3.2 on 2021-11-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20211102_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('rejected', 'rejected'), ('complete', 'complete'), ('cancelled', 'cancelled')], default='initiated', max_length=15),
        ),
        migrations.AddField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('O', 'online'), ('F', 'offline')], default=None, max_length=8),
            preserve_default=False,
        ),
    ]
