# Generated by Django 3.2 on 2021-11-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211106_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('O', 'online'), ('F', 'offline')], default=None, max_length=8),
        ),
    ]
