# Generated by Django 3.2 on 2021-11-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20211112_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.BigIntegerField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='transactions',
            name='currency',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='transactions',
            name='order_id',
            field=models.CharField(default=None, max_length=1000, unique=True),
        ),
    ]
