# Generated by Django 3.2 on 2021-11-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20211112_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transact_id',
            field=models.IntegerField(default=None),
        ),
    ]
