# Generated by Django 3.2 on 2021-11-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20211112_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transact_id',
        ),
    ]
