# Generated by Django 3.2 on 2021-11-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_transactions_transact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transact_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='From_mon',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='To_mon',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currency',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('O', 'online'), ('F', 'offline')], max_length=8, null=True),
        ),
    ]
