# Generated by Django 3.2 on 2021-11-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_transactions_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='From_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='To_year',
            field=models.IntegerField(null=True),
        ),
    ]
