# Generated by Django 3.2 on 2021-11-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20211113_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='Year',
        ),
    ]
