# Generated by Django 3.2 on 2021-11-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_transactions_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transact_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
