# Generated by Django 3.2 on 2021-11-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_transactions_transact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='designation',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
