# Generated by Django 3.2 on 2021-11-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_members_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='flat_type',
            field=models.CharField(max_length=20),
        ),
    ]
