# Generated by Django 3.2 on 2021-11-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_members_flat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='block',
            field=models.CharField(max_length=5),
        ),
    ]
